### ISSUE TITLE
Path length is long enough to cause limit issues

### ISSUE THREAD

**Issue by maf1024** [ygrenier/SharpZipLib.Portable#5]
"SharpZipLib.Portable.0.86.0.0003\lib\portable-net45+netcore45+wp8+win8+wpa81+MonoTouch+MonoAndroid+Xamarin.iOS10\"

This is currently the longest-path nuget library we use, and causes some issues with compiling due to windows limitations.

**Comment by ygrenier** [comment]
Sorry for the delay.

This is the normalized name for the Portable Library it couldn't be changed.

But since the original https://github.com/icsharpcode/SharpZipLib project supports .NET Standard it could be a better solution to use it.

But if you absolutly need the Portable version you have two solutions:
- change your project path to reduce the path name
- fork or clone the repository and add the project directly in your solution, the long name is just for the package, not the Library name.

Regards
